#!/usr/bin/env bash
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/agent-status.env"
EXAMPLE_FILE="$SCRIPT_DIR/agent-status.env.example"
say() {
  printf '%s\n' "$*"
}

ask_default() {
  local prompt="$1"
  local default="$2"
  local answer
  printf '%s [%s]: ' "$prompt" "$default" >&2
  read -r answer
  if [[ -z "$answer" ]]; then
    printf '%s\n' "$default"
  else
    printf '%s\n' "$answer"
  fi
}

ask_optional() {
  local prompt="$1"
  local answer
  printf '%s: ' "$prompt" >&2
  read -r answer
  printf '%s\n' "$answer"
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

shell_quote() {
  local value="$1"
  value="${value//\'/\'\\\'\'}"
  printf "'%s'" "$value"
}

doctor() {
  cd "$SCRIPT_DIR" || exit 1

  say 'Agent Usage Pane doctor'
  say

  if [[ -r "$ENV_FILE" ]]; then
    say "config: ok ($ENV_FILE)"
    # shellcheck disable=SC1090
    . "$ENV_FILE"
  else
    say 'config: missing (run ./install.sh)'
  fi

  if command_exists jq; then say 'jq: ok'; else say 'jq: missing (brew install jq bc)'; fi
  if command_exists bc; then say 'bc: ok'; else say 'bc: missing (brew install jq bc)'; fi
  if command_exists codex; then say "codex: ok ($(command -v codex))"; else say 'codex: missing from PATH'; fi

  local claude_status_file="${CLAUDE_STATUS_FILE:-${AGENT_STATUS_STATE_DIR:-${XDG_RUNTIME_DIR:-$HOME/.cache}/agent-status}/claude-status.json}"
  if [[ -s "$claude_status_file" ]]; then
    say "Claude statusLine JSON: ok ($claude_status_file)"
  else
    say "Claude statusLine JSON: missing ($claude_status_file)"
    say '  configure Claude Code statusLine to run ./claude-status-line.sh'
  fi

  say "Codex app-server command: ${CODEX_APP_SERVER_COMMAND:-codex app-server}"
}

write_env() {
  local bar_width="$1"
  local codex_command="$2"
  local codex_wait_seconds="$3"

  umask 077
  {
    printf '# Generated by install.sh. Edit this file when local settings change.\n'
    printf 'AGENT_STATUS_BAR_WIDTH=%s\n' "$bar_width"
    if [[ "$codex_command" != "codex app-server" ]]; then
      printf 'CODEX_APP_SERVER_COMMAND=%s\n' "$(shell_quote "$codex_command")"
    fi
    if [[ "$codex_wait_seconds" != "10" ]]; then
      printf 'CODEX_APP_SERVER_WAIT_SECONDS=%s\n' "$codex_wait_seconds"
    fi
    printf 'AGENT_STATUS_INTERVAL_SECONDS=60\n'
    printf 'AGENT_STATUS_PANE_REFRESH_SECONDS=3\n'
  } >"$ENV_FILE"
  chmod 600 "$ENV_FILE" 2>/dev/null || true
}

main() {
  cd "$SCRIPT_DIR" || exit 1

  if [[ "${1:-}" == "--doctor" ]]; then
    doctor
    exit 0
  fi

  say 'Agent Usage Pane installer'
  say

  if [[ -e "$ENV_FILE" ]]; then
    say "Existing agent-status.env found."
    local overwrite
    overwrite="$(ask_default 'Overwrite it?' 'no')"
    case "$overwrite" in
      y|Y|yes|YES) ;;
      *) say 'Keeping existing agent-status.env.'; exit 0 ;;
    esac
  elif [[ ! -r "$EXAMPLE_FILE" ]]; then
    say "Missing $EXAMPLE_FILE"
    exit 1
  fi

  if command_exists brew; then
    if ! command_exists jq || ! command_exists bc; then
      say 'Missing jq or bc.'
      say 'Install with: brew install jq bc'
      say
    fi
  fi

  chmod +x "$SCRIPT_DIR/agent-status-daemon.sh" "$SCRIPT_DIR/agent-status-pane.sh" 2>/dev/null || true
  chmod +x "$SCRIPT_DIR/claude-status-line.sh" 2>/dev/null || true

  local bar_width codex_command codex_wait_seconds
  bar_width="$(ask_default 'Pane bar width' '12')"
  codex_command="$(ask_default 'Codex app-server command' 'codex app-server')"
  codex_wait_seconds="$(ask_default 'Codex response wait seconds' '10')"

  write_env "$bar_width" "$codex_command" "$codex_wait_seconds"

  say
  say "Wrote $ENV_FILE"
  say
  say 'Next step:'
  say './agent-status-pane.sh'
}

main "$@"
